import { NativeAttribute } from "../PluginGlobal";
export declare function StatusBarInitialize(pageIndex: NativeAttribute): void;
export declare function StatusBarShow(pageIndex: NativeAttribute): void;
export declare function StatusBarReady(pageIndex: NativeAttribute): void;
export declare function StatusBarBackgroundTextColor(pageIndex: NativeAttribute): void;
export declare function StatusBarStyleDefault(pageIndex: NativeAttribute): void;
export declare function StatusBarOverlays(pageIndex: NativeAttribute): void;
