import { NativeAttribute } from '../PluginGlobal';
export declare function openInAppBrowser(pageIndex: NativeAttribute): void;
export declare function closeInAppBrowser(pageIndex: NativeAttribute): void;
export declare function injectScriptCodeInAppBrowser(pageIndex: NativeAttribute): void;
export declare function injectScriptFileInAppBrowser(pageIndex: NativeAttribute): void;
export declare function injectStyleCodeInAppBrowser(pageIndex: NativeAttribute): void;
export declare function injectStyleFileInAppBrowser(pageIndex: NativeAttribute): void;
